server:
  port: 9884
spring:
  application:
    name: tasklist
  redis:
    host: 192.168.0.105
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册





logging:
  level:
    com.sodkwhy.exam: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

